import { shallowRef } from 'vue';
import { transactionPaymentMethodOptions, transactionStatusOptions } from 'src/repositories/transaction';
import FormBuilderCurrencyInput from 'components/controls/formBuilderCustomInput/FormBuilderCurrencyInput.vue';

const FormBuilderCurrencyInputComponent = shallowRef(FormBuilderCurrencyInput);

export default () => [
  {
    type: FormBuilderCurrencyInputComponent,
    name: 'amount',
    responseKey: 'amount',
    label: 'مقدار',
    disable: true,
    placeholder: ' ',
    col: 'col-md-3 col-12',
  },
  {
    type: 'select',
    name: 'payment_method',
    responseKey: 'payment_method',
    label: 'روش پرداخت',
    options: transactionPaymentMethodOptions,
    placeholder: ' ',
    col: 'col-md-3 col-12',
  },
  {
    type: 'select',
    name: 'transaction_status',
    responseKey: 'transaction_status',
    label: 'وضعیت تراکنش',
    options: transactionStatusOptions,
    value: 'paid',
    placeholder: ' ',
    col: 'col-md-3 col-12',
  },
  {
    type: 'input',
    name: 'authority',
    responseKey: 'authority',
    label: 'کد مرجع',
    placeholder: ' ',
    col: 'col-md-3 col-12',
  },
  {
    type: 'input',
    name: 'transactionID',
    responseKey: 'transactionID',
    label: 'شناسه تراکنش',
    placeholder: ' ',
    col: 'col-md-3 col-12',
  },
  {
    type: 'input',
    name: 'card_pan',
    responseKey: 'card_pan',
    label: 'card_pan',
    placeholder: ' ',
    disable: true,
    col: 'col-md-3 col-12 ltr',
  },
  {
    type: 'dateTime',
    name: 'paid_at',
    responseKey: 'paid_at',
    outsideLabel: 'زمان پرداخت',
    placeholder: ' ',
    iso8601: false,
    col: 'col-md-3 col-12',
  },
  {
    type: 'dateTime',
    name: 'verified_at',
    responseKey: 'verified_at',
    outsideLabel: 'زمان تایید پرداخت',
    placeholder: ' ',
    iso8601: false,
    col: 'col-md-3 col-12',
  },
  {
    type: 'inputEditor',
    name: 'description',
    responseKey: 'description',
    label: 'توضیحات',
    placeholder: ' ',
    col: 'col-md-12 col-12',
  },
  { type: 'separator', name: 'space', size: '0', label: 'اطلاعات درگاه بانک سامان', col: 'col-md-12' },
  {
    type: 'input',
    name: 'saman_transaction.result_description',
    responseKey: 'saman_transaction.result_description',
    label: 'result_description',
    placeholder: ' ',
    disable: true,
    col: 'col-md-3 col-12',
  },
  {
    type: 'input',
    name: 'saman_transaction.result_code',
    responseKey: 'saman_transaction.result_code',
    label: 'result_code',
    placeholder: ' ',
    disable: true,
    col: 'col-md-3 col-12',
  },
  {
    type: 'date',
    name: 'saman_transaction.s_trace_date',
    responseKey: 'saman_transaction.s_trace_date',
    outsideLabel: 's_trace_date',
    placeholder: ' ',
    disable: true,
    col: 'col-md-3 col-12',
  },
  {
    type: 'input',
    name: 'saman_transaction.trace_no',
    responseKey: 'saman_transaction.trace_no',
    label: 'trace_no',
    placeholder: ' ',
    disable: true,
    col: 'col-md-3 col-12',
  },
]
